site_name: OneApp 架构设计文档
site_description: OneApp Flutter应用完整技术架构设计和模块说明
site_author: OneApp Team

# 构建配置
docs_dir: ./docs
site_dir: ./site
# 为静态文件部署优化URL结构
use_directory_urls: false

# Theme
theme:
  name: material
  language: zh
  palette:
    # 浅色模式
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式
    # 深色模式  
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: 切换至浅色模式
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono

# Plugins
plugins:
  - search:
      lang: zh

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # GitHub Flavored Markdown 扩展
  - nl2br
  - sane_lists
  - smarty
  - toc:
      permalink: true
      baselevel: 1
      separator: "_"

# Extra
extra:
  version:
    provider: mike

# Extra JavaScript - 使用最新版本的Mermaid
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10.9.1/dist/mermaid.min.js
  - assets/js/mermaid.js

# Extra CSS
extra_css:
  - assets/css/extra.css

# Navigation - 根据实际文档内容优化
nav:
  - 首页: README.md
  - 架构设计文档: OneApp架构设计文档.md
  - 主应用架构: main_app.md
  - 调试工具: debug_tools.md
  - 账户模块:
      - 概览: account/README.md
      - CLR账户服务: account/clr_account.md
      - 极光验证: account/jverify.md
  - 售后服务:
      - 概览: after_sales/README.md
      - CLR售后服务: after_sales/clr_after_sales.md
      - 售后应用: after_sales/oneapp_after_sales.md
  - 车辆服务:
      - 概览: app_car/README.md
      - AI聊天助手: app_car/ai_chat_assistant.md
      - 高德定位: app_car/amap_flutter_location.md
      - 高德搜索: app_car/amap_flutter_search.md
      - 应用头像: app_car/app_avatar.md
      - 车辆管理: app_car/app_car.md
      - 车辆监控: app_car/app_carwatcher.md
      - 充电服务: app_car/app_charging.md
      - 应用组合: app_car/app_composer.md
      - 维修保养: app_car/app_maintenance.md
      - 订单管理: app_car/app_order.md
      - RPA服务: app_car/app_rpa.md
      - TouchGo: app_car/app_touchgo.md
      - VUR服务: app_car/app_vur.md
      - Wallbox: app_car/app_wallbox.md
      - 车辆服务: app_car/car_services.md
      - CLR虚拟形象: app_car/clr_avatarcore.md
      - CLR订单服务: app_car/clr_order.md
      - CLR TouchGo: app_car/clr_touchgo.md
      - CLR Wallbox: app_car/clr_wallbox.md
      - RPA插件: app_car/kit_rpa_plugin.md
      - 缓存插件: app_car/one_app_cache_plugin.md
      - 头像UI: app_car/ui_avatarx.md
  - 基础UI组件:
      - 概览: basic_uis/README.md
      - 基础UI: basic_uis/basic_uis.md
      - 通用组件: basic_uis/general_ui_component.md
      - UI基础: basic_uis/ui_basic.md
      - UI业务: basic_uis/ui_business.md
  - 基础工具库:
      - 概览: basic_utils/README.md
      - MVVM基础: basic_utils/base_mvvm.md
      - 基础配置: basic_utils/basic_config.md
      - 日志系统: basic_utils/basic_logger.md
      - 网络基础: basic_utils/basic_network.md
      - 平台基础: basic_utils/basic_platform.md
      - 推送基础: basic_utils/basic_push.md
      - 基础工具: basic_utils/basic_utils.md
      - 下载器: basic_utils/flutter_downloader.md
      - MT推送: basic_utils/flutter_plugin_mtpush_private.md
  - 汽车销售:
      - 概览: car_sales/README.md
  - 社区功能:
      - 概览: community/README.md
  - 会员服务:
      - 概览: membership/README.md
  - 服务组件:
      - 概览: service_component/README.md
  - 设置功能:
      - 概览: setting/README.md
  - 触点模块:
      - 概览: touch_point/README.md